#
LOCAL_DIR := $(GET_LOCAL_DIR)

TARGET := oppo6755_65t_c05_l

MODULES += app/mt_boot \
           dev/lcm

MTK_EMMC_SUPPORT = yes
DEFINES += MTK_NEW_COMBO_EMMC_SUPPORT
MTK_KERNEL_POWER_OFF_CHARGING = yes
DEFINES += SWCHR_POWER_PATH
MTK_LCM_PHYSICAL_ROTATION = 180
CUSTOM_LK_LCM="ili9885b_fhd_dsi_vdo_txd_asi_al1518"

#FASTBOOT_USE_G_ORIGINAL_PROTOCOL = yes
MTK_SECURITY_SW_SUPPORT = yes
MTK_VERIFIED_BOOT_SUPPORT = yes
MTK_SEC_FASTBOOT_UNLOCK_SUPPORT = yes

BOOT_LOGO:=cmcc_lte_fhd
DEBUG := 0
#DEFINES += WITH_DEBUG_DCC=1
DEFINES += WITH_DEBUG_UART=1
#DEFINES += WITH_DEBUG_FBCON=1
#DEFINES += MACH_FPGA=y

CUSTOM_LK_USB_UNIQUE_SERIAL=no
