#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y += ili9885_fhd_dsi_vdo_dj_asi_al1518.o 
obj-y += ili9885b_fhd_dsi_vdo_dj_asi_al1518.o




